% --- INICIO DE PLANTILLA PERSONALIZADA ---
\documentclass[oneside,11pt]{Latex/Classes/PhDthesisPSnPDF}

% --- Paquetes Originales ---
\usepackage{blindtext}
\usepackage{actuarialangle} 
\usepackage{tabularx}
\usepackage{float}
\usepackage{multirow, array}
\usepackage[usenames,dvipsnames,svgnames,table]{xcolor}
\usepackage{longtable}
\usepackage{latexsym,amsmath,amssymb,amsfonts}
\usepackage{enumitem}
\usepackage{xparse}
\usepackage{booktabs}
\usepackage[round, sort, numbers]{natbib}  
\usepackage{adjustbox}
\usepackage[utf8]{inputenc}
\usepackage{caption}
\usepackage{graphicx}
\usepackage{hyperref}
\usepackage{cleveref}

% Definición de colores
\definecolor{miblue}{RGB}{68, 114, 196}

% --- CAMBIO CRÍTICO 1: Usar \input para macros en el preámbulo ---
% \include da problemas antes del begin document. \input es seguro.
\input{Latex/Macros/MacroFile1}

% --- Definiciones de seguridad (por si la clase falla al cargar alguna variable) ---
\providecommand{\facultad}[1]{\def\lafacultad{#1}}
\providecommand{\escudofacultad}[1]{\def\elescudo{#1}}
\providecommand{\degree}[1]{\def\elgrado{#1}}
\providecommand{\director}[1]{\def\eldirector{#1}}
\providecommand{\lugar}[1]{\def\ellugar{#1}}
\providecommand{\degreedate}[1]{\def\lafecha{#1}}

% --- Configuración para bloques de código de R (Pandoc) ---

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%                         DATOS (Conectados a RMarkdown)                       %
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
\title{Análisis comparativo de ventas globales de videojuegos de las
empresas Nintendo, Sony y Microsoft}
\author{Mariangela Laya 30849318 \\ Santiago Colmenares 32270162}

% Lógica para Facultad: Si la defines en el YAML la usa, si no, usa la default

\facultad{Facultad de Ciencias Económicas y Sociales \\ Escuela de
Estadistica y Ciencias Actuariales}
  \escudofacultad{Latex/Classes/Escudos/faces}

\degree{Computación I}
\director{Jesus Ochoa \\ Oliver Triveño}
\degreedate{Abril 2026} 
\lugar{Caracas}

\portadatrue 

% Metadatos PDF
\keywords{}
\subject{}

% --- CORRECCIÓN PARA PANDOC NUEVO (Imágenes) ---
\makeatletter
\providecommand{\pandocbounded}[1]{#1}
\makeatother


%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%                   DOCUMENTO                       %
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
\begin{document}

\maketitle

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%                  PRÓLOGO                          %
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
\frontmatter

% Puedes agregar dedicatorias desde el YAML si quieres, o dejarlas fijas aquí

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%                   ÍNDICES                         %
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
\setcounter{secnumdepth}{3}
\setcounter{tocdepth}{3}

\tableofcontents



\cleardoublepage

  \cleardoublepage       % Empieza en página derecha (estándar en tesis)
  \chapter*{Resumen}     % Crea el título "Resumen" sin numeración (Capítulo *)
  \addcontentsline{toc}{chapter}{Resumen} % (Opcional) Lo añade al índice
  
  El presente trabajo ejecuta un análisis estadístico descriptivo y
establece una comparación a las ventas globales por millones de copias
de videojuegos de las empresas Nintendo, Sony y
Microsoft.             % Aquí se pega el texto que escribiste en el YAML
  
  \cleardoublepage

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%                   CONTENIDO (El Corazón)          %
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
\mainmatter
\def\baselinestretch{1.5}

% --- CAMBIO CRÍTICO 2: Aquí RMarkdown inyecta todo tu texto ---
\chapter*{Introducción}

La industria de los videojuegos es un sector económico que con el paso
de los años ha evolucionado el entretenimiento y la tecnología. Una de
las características principales de este mercado es que cambia muy
rápido, lo que hoy puede ser un éxito mañana es un rotundo fracaso. Es
por ello que el presente trabajo se enfoca en el análisis estadístico
descriptivo de las tres empresas más grandes, Nintendo, Sony y
Microsoft, con el fin de caracterizar sus ventas y comportamientos en el
tiempo.

\chapter{Planteamiento del Problema}

Los videojuegos con el paso de los años se han vuelto un sector
financiero de tamaño considerable, llegando a denominarse como la
industria de los videojuegos, donde las empresas pueden valerse de ganar
dinero con distintas estrategias monetizándolos. Sin embargo, la
industria de los videojuegos es muy volátil por distintos factores como
la tecnología, las tendencias, la competencia y la economía global.
Nintendo, Sony y Microsoft se han consolidado como tres de las empresas
más grandes y renombradas dentro de la industria, donde han tenido sus
altas y bajas dentro del mercado a nivel global. La falta de
comparaciones con las ventas netas de cada empresa tiene una repercusión
en el desarrollo de estrategias de ventas dentro de la industria. El
análisis estadístico permite hallar patrones y tendencias, en las que se
visualice el rendimiento de cada empresa y se puedan obtener
comparaciones. Debido a esto, se plantea las siguientes preguntas de
investigación:

\textbf{1.}¿Qué empresa tiene la mayor cantidad de ventas globales?

\textbf{2.}¿Cuál empresa ha tenido el pico más alto de ventas globales?

\textbf{3.}¿Cuáles son los 10 juegos más vendidos entre las tres
empresas?

\section{Justificación}

Nintendo, Microsoft y Sony, no solo compiten entre ellos en el mercado
de los videojuegos, sino que también dictaminan la mayoría de veces las
tendencias tecnológicas y de consumo a nivel mundial en esta área, por
esta razón se quiere cuantificar el impacto real que tienen estas tres
corporaciones en un entorno de alta volatilidad del mercado. Como fue
mencionado anteriormente, existe la falta de comparaciones en las ventas
netas de cada una de estas empresas, ya que sin un análisis estadístico
que compara los datos de ventas globales de estas tres corporaciones,
refiriéndose a los picos de ventas como a los bajones de las mismas, las
estrategias de ventas corren el riesgo de solo basarse en percepciones
cualitativas o intuiciones lógica en vez de datos y evidencias sólidas.
La conclusión de este planteamiento no solo beneficia a analistas
financieros, sino también a desarrolladores del área de los video juego
y publicadores de los mismos interesados en entender las dinámicas de
competencia en el mercado, ya que al finalizar el estudio, se contará
con una visión clara de quién domina el sector y quién en eficiencia de
ventas, permitiendo una visión más acertada sobre el comportamiento
futuro de la industria.

\section{Objetivos}

\subsection{Objetivo General}

Analizar de manera comparativa el desempeño en ventas de videojuegos de
las empresas Nintendo, Sony y Microsoft, con el fin de identificar
patrones, tendencias y productos destacados en el mercado.

\subsection{Objetivos Específicos}
\begin{enumerate}
  \item Cuantificar las ventas totales de cada empresa.
  \item Comparar las ventas anuales de cada empresa en el tiempo.
  \item Determinar el top 10 juegos más vendidos de cada empresa.
\end{enumerate}

\section{Cobertura}

\subsection{Horizontal}

La cobertura horizontal comprende las características de cada videojuego
del dataset . Contienen descripciones cualitativas como por ejemplo el
nombre, el género y la plataforma, mientras que los datos cuantitativos
se refiere a las ventas en determinada región geográfica y los años de
publicación.

\begin{table}[ht]
\centering
\caption{Variables consideradas en el estudio} 
\resizebox{12cm}{!} {
\begin{tabular}{cll}
  \hline
  \textbf{TIPO} & \textbf{VARIABLE} & \textbf{DESCRIPCIÓN} \\ 
  \hline
  Categórica & Name & Nombre comercial del videojuego \\ 
  Numérica & Year & Año de lanzamiento del título \\ 
  Categórica & Publisher & Compañía editora responsable de la distribución \\ 
  Numérica & Global Sales & Suma total de ventas a nivel mundial \\ 
   \hline
\end{tabular}
}
\end{table}

\subsection{Vertical}

La cobertura vertical contiene un total de registros. Cada fila
representa un videojuego publicado. El estudio abarca los juegos de
Nintendo, Sony y Microsoft, con un tiempo desde 1983 hasta 2016.

\section{Periodo de Referencia}

El dataset fue extraido del siguiente drive:
\url{https://drive.google.com/drive/folders/1al-AkIbzbBArFeLP3jn9hD68C0t26Emu}
(12.Video Game Sales.csv). El periodo de referencia para el análisis
descriptivo se centra en el intervalo de 1983-2016.

\section{Variables}

Las variables principales en el estudio son Nintendo, Sony, Microsoft,
estos son los publishers en los que nos basaremos para comparar sus
ventas y determinar cuál de las tres compañías domina el sector y es más
eficiente con sus ventas. Como variables explicativas o independientes
se analizan:

\begin{enumerate}
  \item Variables Temporales: \textbf{Year}
  \item Variables Categóricas: \textbf{Name}
  \item Variables Geográficas: \textbf{Global Sales Millions}
\end{enumerate}

\chapter{Marco Teórico}

\section{Bases Teóricas}

En este capítulo se establecen los fundamentos matemáticos y
estadísticos considerados para realizar el análisis del dataset
videogame sales. La teoría se orienta para responder los objetivos
establecidos y describir los resultados de las empresas en estudio.

\subsection{Medidas estadísticas descriptivas}

Para visualizar el comportamiento de la variable Global Sales de cada
empresa y poder compararlas, se aplican las siguientes medidas:
Sumatoria, para determinar la cantidad total de juegos publicados y
ventas, media y mediana, para resumir el conjunto estudiado, varianza,
desviación típica y coeficiente de variación de Pearson, para medir la
dispersión de los datos.

\subsection{Unidad de medida}

La unidad de medida recolectada toma en cuenta la cantidad de copias
vendidas en millones de unidades, esto incluye ventas en físico y
digital.

\subsection{Ventas Globales}

La variable Global Sales es la sumatoria de las ventas de distintas
partes del mundo, más específicamente de Norteamerica (NA), Europa (EU),
Japón (JP) y el resto del mundo (Other). Siendo expresado en millones de
copias vendidas.

\subsection{Publicador}

Publisher se refiere a la empresa que publicó el videojuego, las
empresas tomadas en cuenta son Nintendo, Sony y Microsoft. Estas
empresas son tanto fabricantes de consolas como editoras. Cabe recalcar,
que cada empresa pública videojuegos sólo para sus propias plataformas.

\subsection{Año de lanzamiento}

Year es la variable que nos indica el año en que oficialmente el juego
fue lanzado al mercado

\subsection{Mercado de videojuegos}

Se define el mercado de videojuegos, como un sector económico dedicado
al entretenimiento, mediante el desarrollo de plataformas y/o
videojuegos.

\subsection{Sector específico del mercado}

El sector de videojuegos en donde se desarrolla el estudio es en la
producción de videojuegos triple A, son videojuegos producidos y
distribuidos por empresas grandes (como las tres en estudio) con
presupuestos de desarrollo y marketing sumamente altos.

\chapter{Marco Metódico}

En el marco metodológico se detallan los procedimientos para la limpieza
de los datos y la aplicación de medidas estadísticas.El análisis se ha
realizado usando el lenguaje de programación R bajo el entorno de
RStudio aplicando la librería de ``Tidyverse'' para la manipulación de
datos.

\section{Bases metódicas utilizadas en el trabajo de investigación}

Esta investigación es de tipo cuantitativo y no experimental, ya que se
describen características de un conjunto de datos observado sin
manipulación directa.

\subsection{Limpieza de Datos}

El proceso de limpieza de datos es uno de los pasos fundamentales para
asegurar un buen análisis. Consiste en la detección de valores faltantes
(N/A) y proceder a imputarlos o eliminarlos. Para el dataset de
videogames sales, se detectaron N/A en las columnas de Publisher y Year.
Se decidió eliminar los N/A, ya que al trabajar con solo 3 empresas,
imputar la variable categórica Publisher no nos servirá posteriormente y
la variable numérica Year no se puede imputar.Luego de eliminar las
columnas que no se van a usar y filtrar las tres empresas quedaron en
total 1567 registros y 5 variables.

\subsection{Aplicación y resultados de las medida estadísticas descriptivas}

Las medidas estadísticas descriptivas son necesarias para poder resumir
el comportamiento de los datos. Se aplican las medidas establecidas en
el capítulo 2 a la variable Global Sales Millions de cada una de las
empresas.

\chapter{Análisis de Resultados}

En este capítulo se presentan los resultados obtenidos al aplicar la
teoría y la metodología definida en capítulos anteriores junto con la
interpretación de los resultados.

\section{Ventas en el tiempo}

Los gráficos de líneas son necesarios para comparar y analizar las
ventas en el tiempo de cada empresa, permitiendo evaluar picos de ventas
facilmente.

\begin{figure}[H]

{\centering \includegraphics[width=0.9\linewidth,]{informe_files/figure-latex/grafico-lineas-1} 

}

\caption{Evolucion de ventas en el tiempo}\label{fig:grafico-lineas}
\end{figure}

En dicho gráfico podemos observar un periodo entre 2000-2010 de ventas
altas para las tres empresas, notablemente más alto para Nintendo.

\section{Top 10 videojuegos por ventas de cada empresa}

Para comparar el top 10 de juegos por ventas de cada empresa, es
necesario la elaboración de gráficos de barras.

\begin{figure}[H]

{\centering \includegraphics[width=0.9\linewidth,]{informe_files/figure-latex/grafico-barra1-1} 

}

\caption{Top 10 en ventas de videojuegos de Nintendo }\label{fig:grafico-barra1}
\end{figure}

\begin{figure}[H]

{\centering \includegraphics[width=0.9\linewidth,]{informe_files/figure-latex/grafico-barra2-1} 

}

\caption{Top 10 en ventas de videojuegos de Sony}\label{fig:grafico-barra2}
\end{figure}

\begin{figure}[H]

{\centering \includegraphics[width=0.9\linewidth,]{informe_files/figure-latex/grafico-barra3-1} 

}

\caption{Top 10 en ventas de videojuegos de Microsoft}\label{fig:grafico-barra3}
\end{figure}

\section{Análisis descriptivo}

\begin{table}[ht]
\centering
\caption{Resultados descriptivos}
\label{tab:resultados}
\resizebox{15cm}{!} {
\begin{tabular}{lcccccccc}
  \hline
  \textbf{Empresa} & \textbf{Publicaciones} &\textbf{Total} & \textbf{Media} &
  \textbf{Mediana} & \textbf{Varianza} & \textbf{Desv. tip.} & \textbf{CV}\\ 
  \hline
  Nintendo & 696 & 1784.43 & 2.56 &  0.92 & 32.23 & 5.68 & 45.16\% \\ 
  Sony & 682 & 607.28 & 0.89 & 0.34 & 2.43 & 1.56 & 57.14\% \\ 
  Microsoft & 189 & 245.79 & 1.3 & 0.36 & 6.42 & 2.53 & 51.34\% \\ 
   \hline
\end{tabular}
}
\end{table}

Tomando en cuenta la tabla \ref{tab:resultados}, encontramos que
Nintendo ha publicado \texttt{696} juegos, ha vendido en total
\texttt{1784.43} millones de copias, con un promedio de \texttt{2.56}
millones de copias vendidos y una mediana de \texttt{0.92}, evidenciando
una distribución asimétrica positiva no solo para Nintendo, sino también
para las otras empresas. Se observa una varianza y desviación típica de
\texttt{32.23} y \texttt{5.68} respectivamente, una dispersión absoluta
sumamente alta junto con una dispersión relativa de \texttt{45.16}\%.

Por otro lado, las empresas Sony y Microsoft tienen un total de
\texttt{682} y \texttt{189} juegos publicados, \texttt{607.28} y
\texttt{245.79} millones de copias. Presentan una media y mediana que
como se mencionó, evidencian una distribución asimétrica positiva. Se
registra además una varianza de \texttt{2.43} y \texttt{6.42} y una
desviación típica de \texttt{1.56} y \texttt{2.53}, lo cual nos indica
una dispersión alta que se confirma con una dispersión relativa de
\texttt{57.14}\% y \texttt{51.34}\%.

\section{ Análisis de ventas en el tiempo y top 10}

En el gráfico \ref{fig:grafico-lineas} se observa un periodo de años
entre 2000-2010 de ventas altas para las tres empresas, más
específicamente 2006 para Nintendo, 2001 para Sony y 2010 para
Microsoft. Por otro lado, a partir de \ref{fig:grafico-barra1}
observamos los top 10 juegos más vendidos de cada empresa.

\section{Análisis Comparativo de las empresas trabajadas utilizando ventas en total por publicaciones en total}

En la tabla \ref{tab:resultados} podemos apreciar como, Nintendo tiene
\texttt{696} publicaciones en total y \texttt{1784.43} millones de
ventas en total, a diferencia de Sony que tiene \texttt{682}
publicaciones en total y \texttt{607.28} millones de ventas en total,
por otro lado tenemos a Microsoft con \texttt{189} publicaciones en
total y \texttt{245.79} millones de ventas en total, en este caso
podemos decir que a simple vista el análisis comparativo es que entre
mas juegos publiquen las empresas, más ventas logran, pero en realidad
es un poco más extensivo que eso. Cuando comparamos Nintendo con Sony
notamos como Nintendo tiene publicado catorce juegos por arriba que
Sony, esto no solo conlleva a que las empresas de videojuegos entre más
demanda tengan, mas juegos publican, como lo vemos en el caso de
Microsoft que al tener poca demanda, a comparación de las otras dos
empresas tiene muy pocas publicaciones, pero esto también se debe a que
tipo de publico este orientado el marketing o los juego que publiquen
cada una de estas tres empresas, si hablamos de Microsoft esta se enfoca
a un público más adulto con capacidad monetaria, ya que involucra pagar
suscripción, además de la consola donde se puede jugar su catálogo de
juegos, al tener estas condiciones reduce su público a adultos y con
trabajos fijos para pagar la mensualidad al jugar, por otro lado tenemos
a Sony, recordemos que este no esta tan alejado del numero de
publicaciones de Nintendo, pero si de sus ventas, Sony se enfoca a un
publico un poco mas experto, jugadores que buscan alta definicion en sus
juegos, se puede decir que son jugadores ``hardcore'', los cuales ademas
de alta definicion, buscan juegos narrativos e inmersivos, claramente al
basarse en este tipo de publico reduce su demanda, ya que no hay tantos
jugadores de esta rama, por ultimo tenemos a Nintendo el que domina las
ventas entre estas tres empresas, esto se debe a que Nintendo, ademas de
que empezo mucho antes, no solo se enfoco en adultos, sino en toda la
familia y todas las edades, esto hizo que su demanda fuera más alta que
la de las otras dos empresas, volviéndola la empresa con más ventas y
por ende con más juegos publicados en comparación de Sony y Microsoft.

\chapter{Conclusiones y Recomendaciones}

El presente estudio ha permitido describir y comparar el desempeño de
ventas de las empresas Nintendo, Sony y Microsoft, a través del análisis
estadístico descriptivo. A continuación se presentan.\\

\textbf{1.-} Las ventas netas de Nintendo, Sony y Microsoft fueron de
\texttt{1784.43}, \texttt{607.28} y \texttt{245.79} millones de copias
respectivamente, todo en el periodo de 1983-2016.\\

\textbf{Recomendación} Para una cuantificación de ventas netas se
recomienda trabajar con una base de datos más actualizada, para tener en
cuenta los resultados de los últimos años.\\

\textbf{2.-} Se encontró por medio del gráfico \ref{fig:grafico-lineas},
que Nintendo tiene el pico más alto de ventas con más de 200 millones de
copias vendidas en el año 2006, esto se debió a una estrategia para
dominar el mercado que buscaba atraer a personas que normalmente no
jugaban videojuegos, además de que lanzó la consola Wii, una consola que
apostó por el control por movimiento y una versión nueva de su anterior
consola exitosa Nintendo DS. Todo esto más el fácil acceso a la consola
por precio en comparación a las consolas de la competencia, y los
videojuegos lanzados fueron un éxito masivo.

Por otro lado Sony y Microsoft tuvieron un pico de ventas en 2001 y
2010, de 49 y 50 millones de copias vendidas en esos años
respectivamente. Sony en 2000 lanzó la PS2, la cual recibió en 2001
muchos títulos exclusivos sumamente valiosos para la comunidad, además
se suma que la PS2 fue el reproductor de DVD más barato del mercado en
ese momento, lo que aumentó la base de usuarios. Para el 2010, Microsoft
ya no era una empresa nueva, ya había consolidado una base de fans.
Decidieron lanzar en ese año un rediseño de su consola principal Xbox
360 que tenía wi-fi integrado para juegos competitivos online y una
parte para streaming, además de una competencia directa de la Wii
llamada Kinect.\\

\textbf{Recomendación} Para una comparación más exhaustiva se recomienda
tener en cuenta las ventas de las consolas que las empresas hayan
producido.\\

\textbf{3.-} Se determinó el top 10 juegos por ventas globales de las
tres empresas, a partir del gráfico \ref{fig:grafico-barra1}. El top 10
de Nintendo está compuesto en su gran mayoría por juegos de la Wii, lo
cual como se comentó previamente, fue un éxito para Nintendo por su
fácil acceso. Por otro lado Sony y Microsoft presentaron esas ventas
cuando innovaron con una nueva consola y con el lanzamiento de juegos
exclusivos que mantuvieron a un público fiel.\\

\textbf{Recomendación} Se recomienda al igual que con la conclusión 1,
tener una base de datos actualizada y hacer un análisis tomando en
cuenta el género de los videojuegos.

\appendix
\renewcommand{\thechapter}{\Alph{chapter}}

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%                   REFERENCIAS                     %
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% Mantenemos la estructura natbib de tu plantilla
\renewcommand{\bibname}{Lista de Referencias}
\bibliographystyle{apalike} 
\bibliography{bibliografia.bib} 

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%                   APÉNDICES                       %
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

\end{document}
